// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'GOOGLE_API_KEY',
    appId: '1:24488369423:android:0fcf0d83508f08c27d727a',
    messagingSenderId: '24488369423',
    projectId: 'socially-app1',
    databaseURL: 'https://socially-app1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'socially-app1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'GOOGLE_API_KEY_RANDOM',
    appId: '1:24488369423:ios:abb741975cee9b4d7d727a',
    messagingSenderId: '24488369423',
    projectId: 'socially-app1',
    databaseURL: 'https://socially-app1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'socially-app1.appspot.com',
    androidClientId: '24488369423-frh7clqidjs13lt78qmsn148ahj9bb4l.apps.googleusercontent.com',
    iosClientId: '24488369423-ak7q5gibiu2cchj81i9ma8g35ul0eg8r.apps.googleusercontent.com',
    iosBundleId: 'com.example.businessCard',
  );
}
